site_name: Prajwal's Personal Wiki

theme:
  name: material

nav:
  - Home: index.md
  - Machine Learning:
      - Linear Regression: linearRegression.md
      - Generative Adversarial Networks: Generative Adversarial Networks.md


markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax-config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/justify.css
